#########################################
# --- Default Options for All Pages --- #
#########################################

defaults:
  - scope:
      path: ""
    values:
      body: [cook, menu, page, foot]