#########################################
# --- Default Options for All Pages --- #
#########################################

defaults:
  - scope:
      path: ""
    values:
      layout: "one-column"
